name: Check types
on:
  workflow_call:
env:
  NODE_OPTIONS: "--max-old-space-size=8192"
jobs:
  check-types:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/dangerous-git-checkout
      - uses: ./.github/actions/yarn-install

      - name: Show info
        run: node -e "console.log(require('v8').getHeapStatistics())"

      - run: yarn type-check
